# Generated by Django 3.1.3 on 2020-12-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_description',
            new_name='question_instructions',
        ),
    ]
