# Generated by Django 3.1.3 on 2020-12-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201206_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_reading',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_topic',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
