# Generated by Django 3.1.3 on 2020-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
