# Generated by Django 3.1.3 on 2020-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('Other', 'Other'), ('Missions', 'Missions'), ('Spacecraft', 'Spacecraft'), ('Spacesuits', 'Spacesuits'), ('Spaceships', 'Spaceships'), ('NASA Names', 'NASA Names')], default='Other', max_length=100),
        ),
    ]
