# Generated by Django 3.1.3 on 2020-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201213_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('Other', 'Other'), ('Missions', 'Missions'), ('Spacecraft', 'Spacecraft'), ('Spacesuits', 'Spacesuits'), ('NASA Names', 'NASA Names')], default='Other', max_length=100),
        ),
    ]
